// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNewInstruct() {
  return window['go']['instruct']['InstructionBoard']['GetNewInstruct']();
}

export function InstructionAlert(arg1) {
  return window['go']['instruct']['InstructionBoard']['InstructionAlert'](arg1);
}

export function InstructionError(arg1) {
  return window['go']['instruct']['InstructionBoard']['InstructionError'](arg1);
}

export function InstructionInfo(arg1) {
  return window['go']['instruct']['InstructionBoard']['InstructionInfo'](arg1);
}

export function ReceiveInstruct() {
  return window['go']['instruct']['InstructionBoard']['ReceiveInstruct']();
}

export function Startup(arg1) {
  return window['go']['instruct']['InstructionBoard']['Startup'](arg1);
}
