// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {instruct} from '../models';
import {context} from '../models';

export function GetNewInstruct():Promise<instruct.Instruct>;

export function InstructionAlert(arg1:string):Promise<void>;

export function InstructionError(arg1:string):Promise<void>;

export function InstructionInfo(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
