// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screenBox} from '../models';
import {reloadPoint} from '../models';
import {main} from '../models';

export function AddNewScreenBox(arg1:number):Promise<screenBox.ScreenBox>;

export function AssignReloadButton(arg1:number):Promise<reloadPoint.MousePoint>;

export function DeleteGroup(arg1:number,arg2:main.InstructionError):Promise<number>;

export function NewCaptureGroup(arg1:number):Promise<void>;

export function StartOverwatch(arg1:number):Promise<void>;

export function StopOverwatch(arg1:number):Promise<void>;
