// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddNewScreenBox(arg1) {
  return window['go']['main']['App']['AddNewScreenBox'](arg1);
}

export function AssignReloadButton(arg1) {
  return window['go']['main']['App']['AssignReloadButton'](arg1);
}

export function DeleteGroup(arg1, arg2) {
  return window['go']['main']['App']['DeleteGroup'](arg1, arg2);
}

export function NewCaptureGroup(arg1) {
  return window['go']['main']['App']['NewCaptureGroup'](arg1);
}

export function StartOverwatch(arg1) {
  return window['go']['main']['App']['StartOverwatch'](arg1);
}

export function StopOverwatch(arg1) {
  return window['go']['main']['App']['StopOverwatch'](arg1);
}
